version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: chat-mongo
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_DATABASE=chat
    volumes:
      - ./database/mongo:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  cache:
    image: redis:6.2-alpine
    container_name: chat-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./database/redis:/data
volumes:
  cache:
    driver: local